name: youtube_api
description: YouTubeAPI is a plugin which directly interacts with YouTube
  server. Supports Searching video and playlist.
version: 0.9.1
homepage: https://github.com/nitishk72/Youtube_API
repository: https://github.com/nitishk72/Youtube_API

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  collection: ^1.15.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.github.nitishk72.youtubeapi.youtubeapi
        pluginClass: YoutubeApiPlugin
      ios:
        pluginClass: YoutubeApiPlugin
